version: '3.8'
services:
  db:
    container_name: db-container
    image: postgres:9.6
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
