import React from 'react';
import Head from "next/head";

interface Props {
  title?: string;
  children: React.ReactNode;
}

const MainTemplate: React.FC<Props>  = ({ title, children }: Props) => {
  return <>
    <Head>
      <title>{ title } | Authela</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {children}
  </>;
};

export default MainTemplate;
