import React from 'react';
import Head from "next/head";

const MainTemplate: React.FC  = ({ children }) => {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {children}
  </>;
};

export default MainTemplate;
