name: frontend CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install backend modules
        working-directory: ./backend
        run: npm install
      - name: Build frontend
        working-directory: ./backend
        run: npm run build
