name: backend CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install frontend modules
        working-directory: ./frontend
        run: npm install
      - name: Codegen grahpql
        working-directory: ./frontend
        run: npm run codegen
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
